name: Block Suggestion
description: Create a block suggestion to help expand the blocks Architecture Extensions has to offer.
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your block suggestion! If you want to discuss your suggestion, join us on Discord.
        Make sure you are running the latest version of Architecture Extensions before making the suggestion.
  - type: textarea
    id: block-list
    attributes:
      label: List the blocks you want added to AE.
      value: |
        - Crown Molding blocks
        - Cobblestone columns
    validations:
      required: true
  - type: checkboxes
    id: blocktypes
    attributes:
      label: What blocktypes do your block(s) fall under.
      description: You may select more than one.
      options:
        - label: Column Block
        - label: Arch Block
        - label: Post Block
  - type: textarea
    id: description
    attributes:
      label: Describe how these blocks will work if applicable..
      description: "Describe the suggestion as clearly as possible. More info means the suggestion is more likely to be accepted."
      value: |
        The crown molding blocks can be placed on ceilings to add extra detail to a space.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the block suggestion here."
