blank_issues_enabled: false
contact_links:
  - name: Discuss Architecture Extensions related stuff on our Discord server
    url: https://discord.gg/SN89y7EQTN
    about: Discuss bug reports, suggestions or Architecture Extensions related stuff on our Discord server
