blank_issues_enabled: false
contact_links:
  - name: Discuss Architecture Extensions on the Discord server.
    url: https://debuggy.gay/discord
    about: Discuss bug reports, suggestions or other Arch-Ex related stuff on our Discord server.
